notifications:
  email: false

language: go
go:
  - "1.10.x"

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
