version: 2.1

orbs:
  codecov: codecov/codecov@1.1.1
  plugin-ci: mattermost/plugin-ci@0.1.4

workflows:
  version: 2
  main:
    jobs:
      - plugin-ci/lint:
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/coverage:
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - plugin-ci/lint
            - plugin-ci/coverage
      - plugin-ci/deploy-release-github:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - plugin-ci/build
