[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  version = "5.2.0-rc2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
